### ISSUE TITLE
how to get my private key to use the services integrated with java api?

### ISSUE THREAD

**Issue by cristianokiki** [singnet/snet-sdk-java#75]
sorry if I'm in the wrong place to post this question, but I've searched a lot on the workshop site but I couldn't find it, could someone guide me how to get my private key to use the services integrated with java api?

**Comment by vsbogd** [comment]
Hi @cristianokiki , which software do you use to manage your private keys? It can be different for different software.

**Comment by cristianokiki** [comment]
> Hi @cristianokiki , which software do you use to manage your private keys? It can be different for different software.

was trying to connect to the following service: https://singnet.github.io/dnn-model-services/users_guide/cntk-image-recon.html , following the git example: https://github.com/vsbogd/snet-sdk-java,
I set up the git example on my machine, but I don't know where to get my private key

**Comment by vsbogd** [comment]
@cristianokiki , if you didn't generate the wallet yet, then you need to do it first. It can be done by various ways. For example one can use SingularityNet `snet-cli` tool, Ethereum command line tool or MetaMask browser plugin. 

For example, 
- [download and install metamask](https://metamask.io/)
- by default metamask will suggest you creating an Ethereum wallet, follow the instructions
- [export private key from MetaMask](https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key)

**Comment by vsbogd** [comment]
You can also try services using [FreeCallPaymentStrategy](https://javadoc.jitpack.io/com/github/singnet/snet-sdk-java/snet-sdk-java/master-1198d7abdc-1/javadoc/io/singularitynet/sdk/paymentstrategy/FreeCallPaymentStrategy.html). You will still need a private key but will not need `AGIX` tokens on your wallet. 

In order to use it go to the [service page](https://beta.singularitynet.io/servicedetails/org/snet/service/cntk-image-recon), switch to `Install and Run` tab, and enter public Ethereum address of your wallet at the end of the page. Then use values from resulting JSON to initialize [FreeCallAuthToken](https://javadoc.jitpack.io/com/github/singnet/snet-sdk-java/snet-sdk-java/master-1198d7abdc-1/javadoc/io/singularitynet/sdk/freecall/FreeCallAuthToken.Builder.html). Unfortunately we don't have an example of the code yet, but it should be easy to add one.

**Comment by vsbogd** [comment]
@cristianokiki , does above answer your question? May I close the issue?
